FROM node:24-alpine3.22 AS deps

WORKDIR /usr/src/app

COPY package*.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

ENV NODE_ENV=development

EXPOSE 3008

CMD ["npm", "run", "start:dev"]
